# Generated by Django 3.1.5 on 2021-01-18 10:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRecord',
            fields=[
                ('recordID', models.AutoField(primary_key=True, serialize=False)),
                ('patientID', models.PositiveIntegerField()),
                ('patient_document', models.FileField(blank=True, null=True, upload_to='patient_document')),
                ('current_medication', models.TextField(blank=True, max_length=500, null=True)),
                ('temperature', models.CharField(blank=True, max_length=20, null=True)),
                ('allergies', models.TextField(blank=True, max_length=500, null=True)),
                ('presenting_problems', models.TextField(blank=True, max_length=500, null=True)),
                ('assessments', models.TextField(blank=True, max_length=500, null=True)),
                ('plan', models.TextField(blank=True, max_length=500, null=True)),
                ('lab_request', models.FileField(blank=True, null=True, upload_to='lab_request')),
                ('prescription', models.FileField(blank=True, null=True, upload_to='prescription')),
                ('consultation_date', models.DateField(blank=True, default=datetime.datetime(2021, 1, 18, 18, 59, 31, 248654), null=True)),
                ('consultation_time', models.TimeField(blank=True, default=datetime.datetime(2021, 1, 18, 18, 59, 31, 248654), null=True)),
                ('next_consultation_date', models.DateField(blank=True, null=True)),
                ('physicianID', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('physicianID', models.AutoField(primary_key=True, serialize=False)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('landline', models.CharField(blank=True, max_length=20, null=True)),
                ('specialization', models.CharField(choices=[('Anesthesiologist', 'Anesthesiologist'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Family Physician', 'Family Physician'), ('Internal Medicine Physician', 'Internal Medicine Physician'), ('Nephrologist', 'Nephrologist'), ('OB/GYN', 'OB/GYN'), ('Oncologist', 'Oncologist'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Radiologist', 'Radiologist')], max_length=50)),
                ('hospital_affiliation', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('application_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.AutoField(primary_key=True, serialize=False)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('landline', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_doctor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_doctor_approve', models.BooleanField(default=False)),
                ('application_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
