# Generated by Django 3.1.5 on 2021-01-19 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemed', '0002_auto_20210120_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrecord',
            name='consultation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 20, 7, 46, 29, 314748), null=True),
        ),
        migrations.AlterField(
            model_name='consultationrecord',
            name='consultation_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 20, 7, 46, 29, 314748), null=True),
        ),
    ]
