# Generated by Django 3.1.5 on 2021-01-20 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemed', '0003_auto_20210120_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrecord',
            name='consultation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 20, 11, 41, 42, 463318), null=True),
        ),
        migrations.AlterField(
            model_name='consultationrecord',
            name='consultation_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 20, 11, 41, 42, 463318), null=True),
        ),
        migrations.AlterField(
            model_name='physician',
            name='profile_pic',
            field=models.ImageField(upload_to='prof_pics/'),
        ),
    ]
