# Generated by Django 3.1.5 on 2021-01-20 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemed', '0004_auto_20210120_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrecord',
            name='assigned_physician_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='assigned_physician_specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='patient_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='physician_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultationrecord',
            name='consultation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 20, 21, 7, 29, 766946), null=True),
        ),
        migrations.AlterField(
            model_name='consultationrecord',
            name='consultation_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 20, 21, 7, 29, 766946), null=True),
        ),
    ]
